title: Research Centre Schema Library
description: A library of schemas used by the research centres
theme: just-the-docs

url: https://agrifooddatacanada.github.io/AGRFD_library

aux_links:
  Template Repository: https://github.com/agrifooddatacanada/AGRFD_library
